\documentclass[italian,master]{unibg}
\usepackage{graphicx}
\usepackage{amssymb}
\usepackage{multirow}
\usepackage{matlab-prettifier}
\usepackage{tikz}

\title{A Seclab Thesis}
\subtitle{A Seclab Subtitle}
\advisor{Chiar.mo Prof.~John Smith}
% \coadvisor{Chiar.mo Prof.~Ed Smith}

\department{Ingegneria Gestionale, dell'Informazione e della Produzione}
\course{Ingegneria Informatica}
\class{LM-32}

\author{John Doe}
\studentid{177013}
\academicyear{2021/2022}

\begin{document}
\maketitle
\emptypage

\begin{abstract}
    This paper explores the implications of integrating advanced computational models into everyday decision-making processes. By analyzing the interplay between data-driven approaches and human intuition, we aim to identify key opportunities and challenges in fostering collaboration between artificial intelligence and human expertise. The results of our study indicate significant potential for enhancing productivity across diverse domains, while also underscoring the need for ethical considerations and transparency in algorithmic design. Future work will focus on extending these findings to real-world applications and further refining the proposed frameworks.
\end{abstract}

\emptypage
\toc
\listoffigures
\listoftables
\emptypage

\clearpage
\pagenumbering{arabic}

\input{chapters/chap01.tex}




\nocite{*}
\printbibliography[heading=bibintoc]

\end{document}
