\babel@toc {italian}{}\relax 
\babel@toc {italian}{}\relax 
\contentsline {chapter}{\numberline {1}Iterazione 0}{1}{chapter.1}%
\contentsline {section}{\numberline {1.1}Introduzione}{1}{section.1.1}%
